# Generated by Django 4.0.4 on 2022-05-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('genre', models.CharField(choices=[('Drama', 'Drama'), ('Horror', 'Horror'), ('Comedy', 'Comedy'), ('Education', 'Education'), ('Sci-Fi', 'Sci-Fi'), ('Manga', 'Manga'), ('Romantic', 'Romantic')], max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('age_control', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
